server:
  port: 8083
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    datasource:
      platform: h2
      schema:classpath: schema.sql
      data:classpath: data.sql
  application:
    name: microservice-provider-user
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
    perefer-ip-address: true
    metadata-map:
      my-metadata: 我自定义的元数据
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACER

